### ISSUE TITLE
Can't find conda_merge

### ISSUE THREAD

**Issue by Bayesianworld** [microsoft/InnerEye-DeepLearning#664] opened 2022-02-17 20:41 UTC
Just installing the IE-DeepLearning software.  Set up Anaconda and IE software.  When I try running the HelloWorld model, I get the following error:

```python-traceback
~username/mydir:~$ conda activate InnerEye
(InnerEye) ~username/mydir~$ export PYTHONPATH=`pwd`
(InnerEye) ~username/mydir:~$ python InnerEye/ML/runner.py --model=HelloWorld
Starting InnerEye runner at InnerEye/ML/runner.py
Traceback (most recent call last):
  File "InnerEye/ML/runner.py", line 30, in <module>
    from health_azure import AzureRunInfo, submit_to_azure_if_needed
  File "/users/markp/Projects/Microsoft/InnerEye2022/InnerEye-DeepLearning/hi-ml/hi-ml-azure/src/health_azure/__init__.py", line 6, in <module>
    from health_azure.datasets import DatasetConfig
  File "/users/markp/Projects/Microsoft/InnerEye2022/InnerEye-DeepLearning/hi-ml/hi-ml-azure/src/health_azure/datasets.py", line 15, in <module>
    from health_azure.utils import PathOrString, get_workspace
  File "/users/markp/Projects/Microsoft/InnerEye2022/InnerEye-DeepLearning/hi-ml/hi-ml-azure/src/health_azure/utils.py", line 20, in <module>
    import conda_merge
ModuleNotFoundError: No module named 'conda_merge'
```

[AB#5020](https://innereye.visualstudio.com/60ce1777-00d6-4015-82bc-488a0c00202f/_workitems/edit/5020)

**Comment by ant0nsc** [comment] 2022-02-21 15:00
Hi @Bayesianworld , that's a little puzzling. The environment definition does contain conda-merge, [link](https://github.com/microsoft/InnerEye-DeepLearning/blob/e2ec5cc839d07ea9eb0c3a5add3b233daddd9198/environment.yml#L21)
To double-check your environment is set up correctly, can you run
```
conda activate InnerEye
pip freeze | grep conda
```
It should output a line for conda-merge.

**Comment by Bayesianworld** [comment] 2022-02-22 22:18
Tried your suggestion.  Returned immediately with no output.  Here is my session:

markp@lambda:~$ ls
InnerEye-DeepLearning/
markp@lambda:~$ cd InnerEye-DeepLearning/
markp@lambda:~$ conda activate InnerEye
(InnerEye) markp@lambda:~$ export PYTHONPATH=`pwd`
(InnerEye) markp@lambda:~$ pip freeze | grep conda
(InnerEye) markp@lambda:~$ python InnerEye/ML/runner.py --model=HelloWorld
Starting InnerEye runner at InnerEye/ML/runner.py
Traceback (most recent call last):
  File "InnerEye/ML/runner.py", line 30, in <module>
    from health_azure import AzureRunInfo, submit_to_azure_if_needed
  File "/users/markp/Projects/Microsoft/InnerEye2022/InnerEye-DeepLearning/hi-ml/hi-ml-azure/src/health_azure/__init__.py", line 6, in <module>
    from health_azure.datasets import DatasetConfig
  File "/users/markp/Projects/Microsoft/InnerEye2022/InnerEye-DeepLearning/hi-ml/hi-ml-azure/src/health_azure/datasets.py", line 15, in <module>
    from health_azure.utils import PathOrString, get_workspace
  File "/users/markp/Projects/Microsoft/InnerEye2022/InnerEye-DeepLearning/hi-ml/hi-ml-azure/src/health_azure/utils.py", line 20, in <module>
    import conda_merge
ModuleNotFoundError: No module named 'conda_merge'

**Comment by ant0nsc** [comment] 2022-02-23 10:28
Odd. Can you please post the output of running `pip freeze` in your conda environment?
Can you please also check that you are on the latest version of the InnerEye code, and then update your conda environment via `conda env update --file environment.yml`?

**Comment by Bayesianworld** [comment] 2022-02-25 18:24
Hi Anton,
Thanks for the response.  Nothing returned after I ran "pip freeze".  I was wondering if perhaps I don't have the correct directory structure.  On the github issues you can see where I executed the commands.  In general, this is what I consider my InnerEye root directory:

/users/markp/Projects/Microsoft/InnerEye2022/InnerEye-DeepLearning/

That's the directory I run "pip freeze", set PYTHONPATH, and "conda activate InnerEye"

Is this correct?
Thanks,
Mark
________________________________

**Comment by ant0nsc** [comment] 2022-03-01 09:20
Hi Mark - sorry, I may have been a bit too brief with my suggestion. I'm interested in the output of `pip freeze` inside the `InnerEye` environment, _without any filters_, so you would need to run:
```
conda activate InnerEye
pip freeze
```
It should not matter which directory you run that in.

**Comment by Bayesianworld** [comment] 2022-03-01 20:23
Hi Anton,
I have attached a .txt file with the output.
THanks,
Mark
________________________________

**Comment by ant0nsc** [comment] 2022-03-02 22:04
That's all rather odd. I don't get why you don't have conda_merge in your environment, even though you say you built it with the latest environment.yml file. In addition, there are two odd things in your environment: numpy and pillow have these odd "@ file" versions. I'd suggest manually fixing all three by doing
```
conda activate InnerEye
pip uninstall numpy Pillow
pip install conda-merge numpy pillow
```

**Comment by Bayesianworld** [comment] 2022-03-03 01:05
I followed your instructions then tried the HelloWorld model. This was the result:

***@***.***:~$ conda activate InnerEye
(InnerEye) ***@***.***:~$ export PYTHONPATH=`pwd`
(InnerEye) ***@***.***:~$ python InnerEye/ML/runner.py --model=HelloWorld
Starting InnerEye runner at InnerEye/ML/runner.py
Traceback (most recent call last):
  File "InnerEye/ML/runner.py", line 30, in <module>
    from health_azure import AzureRunInfo, submit_to_azure_if_needed
  File "/users/markp/Projects/Microsoft/InnerEye2022/InnerEye-DeepLearning/hi-ml/hi-ml-azure/src/health_azure/__init__.py", line 7, in <module>
    from health_azure.himl import (AzureRunInfo, create_crossval_hyperdrive_config, create_run_configuration,
  File "/users/markp/Projects/Microsoft/InnerEye2022/InnerEye-DeepLearning/hi-ml/hi-ml-azure/src/health_azure/himl.py", line 24, in <module>
    from azureml.core.runconfig import DockerConfiguration, MpiConfiguration
ImportError: cannot import name 'DockerConfiguration' from 'azureml.core.runconfig' (/usr/local/conda/miniconda3/envs/InnerEye/lib/python3.7/site-packages/azureml/core/runconfig.py)
(InnerEye) ***@***.***:~$
________________________________

**Comment by Bayesianworld** [comment] 2022-03-03 20:58
I have attached two .png images with model building and inference workflows.
Mark
________________________________

**Comment by ant0nsc** [comment] 2022-03-03 22:58
Hi @Bayesianworld , Something is really really broken with your conda environment. I checked in the output of `pip freeze` that you posted the other day - it contains azureml-sdk version 1.12.0, but it should be 1.36.0. Hence the problem with DockerConfig, which did not exist in 1.12. It would probably be best if you completely remove that conda environment, and re-build it using the environment definition from the latest InnerEye code in main branch.

Also, just FYI, it seems you are replying to the github comments via email - unfortunately, attachments don't come through there, apart from .txt files

**Comment by Bayesianworld** [comment] 2022-03-04 20:48
Hi Anton,
I have removed the previous install of InnerEye and using the instructions at https://github.com/microsoft/InnerEye-DeepLearning I reinstalled the software.  I tried to run the HelloWorld model and got an error.  Below is a screenshot of my commands and the results.  I have also attached a .txt file with the output from 'pip freeze'.  Thanks for any help,
Mark
-------------------------
(InnerEye) ***@***.***:~$ pwd
/users/markp/Projects/Microsoft/InnerEye2022/InnerEye-DeepLearning
(InnerEye) ***@***.***:~$ python InnerEye/ML/runner.py --model=HelloWorld
Starting InnerEye runner at InnerEye/ML/runner.py
Traceback (most recent call last):
  File "InnerEye/ML/runner.py", line 30, in <module>
    from health_azure import AzureRunInfo, submit_to_azure_if_needed
  File "/users/markp/Projects/Microsoft/InnerEye2022/InnerEye-DeepLearning/hi-ml/hi-ml-azure/src/health_azure/__init__.py", line 7, in <module>
    from health_azure.himl import (AzureRunInfo, create_crossval_hyperdrive_config, create_run_configuration,
  File "/users/markp/Projects/Microsoft/InnerEye2022/InnerEye-DeepLearning/hi-ml/hi-ml-azure/src/health_azure/himl.py", line 24, in <module>
    from azureml.core.runconfig import DockerConfiguration, MpiConfiguration
ImportError: cannot import name 'DockerConfiguration' from 'azureml.core.runconfig' (/usr/local/conda/miniconda3/envs/InnerEye/lib/python3.7/site-packages/azureml/core/runconfig.py)
(InnerEye) ***@***.***:~$

________________________________

**Comment by ant0nsc** [comment] 2022-03-07 09:04
Unfortunately, I’m unable to reproduce the environment creation issue that you are facing. I just created a fresh enlistment, created a brand-new environment, and the HelloWorld models runs just fine.

Are you in a locked-down environment that uses pypi package mirrors or something alike? I have no other hypothesis what could have caused the problems with the AML packages – your environment has version 1.12.0, but we need 1.32.0.

**Comment by ant0nsc** [comment] 2022-05-16 12:57
Closing for lack of more information.

**Closed by ant0nsc** 2022-05-16 12:57 UTC
